### ISSUE TITLE
PostgreSQL client cert support

### ISSUE THREAD

**Issue by riptl** [lijunwangs/solana-accountsdb-plugin-postgres#1]
Google Cloud SQL enforces the use of TLS client certs.
The accounts plugin currently does not support specifying CA/cert file/key file, so it cannot securely connect to Google Cloud SQL directly.

Until then `cloud_sql_proxy` is sufficient as a workaround.

**Comment by lijunwangs** [comment]
Will look into this. Thanks!

**Comment by lijunwangs** [comment]
Fixed and checked into the main repo
