### ISSUE TITLE
Pointers for running `cargo test` on macOS arm64

### ISSUE THREAD

**Issue by levicook** [lijunwangs/solana-accountsdb-plugin-postgres#4]
This is less issue and more FYI on how I got `cargo test` to pass on 

1. Setup the database:
```bash
brew install postgresql
brew services restart postgresql
createdb -O solana solana
psql -U solana -p 5432 -h localhost -w -d solana -f scripts/create_schema.sql
```

2. Build the library
```bash
cargo build --lib
```

3. Make the `farf` directory (not 100% sure the tests don't entirely run in a temp directory)

4. Patch up the test with some platform specific stuff (there's probably a better way to deal with this; just went brute force for expediency)
```bash
diff --git a/tests/test_postgres_plugin.rs b/tests/test_postgres_plugin.rs
index 617fef1..59345bb 100644
--- a/tests/test_postgres_plugin.rs
+++ b/tests/test_postgres_plugin.rs
@@ -122,7 +122,7 @@ fn generate_accountsdb_plugin_config() -> (TempDir, PathBuf) {

     let config_content = r#"
     {
-        "libpath": "libsolana_accountsdb_plugin_postgres.so",
+        "libpath": "libsolana_accountsdb_plugin_postgres.dylib",
         "connection_str": "host=localhost user=solana password=solana port=5432",
         "threads": 20,
         "batch_size": 20,
@@ -210,10 +210,12 @@ fn test_postgres_plugin() {
     solana_logger::setup_with_default(RUST_LOG_FILTER);

     unsafe {
-        let lib = Library::new("libsolana_accountsdb_plugin_postgres.so");
+        let filename = "libsolana_accountsdb_plugin_postgres.dylib";
+        let lib = Library::new(filename);
         if lib.is_err() {
             info!(
-                "Failed to load the dynamic library libsolana_accountsdb_plugin_postgres.so {:?}",
+                "Failed to load the dynamic library {} {:?}",
+                filename,
                 lib
             );
             return;
```

OS Specifics for anyone else that might be looking for this:
```bash
uname -a
Darwin zola.local 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:01 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T6000 arm64
```

**Comment by levicook** [comment]
Partly sharing this because it was a lot easier than I expected it to be. If anyone happens to know the best way to sort out `.so` vs `.dyld` I'd be happy to submit a PR.

**Comment by lijunwangs** [comment]
Maybe first dynamically detect the OS?

**Comment by levicook** [comment]
I'll look into that! Will probably just start with matching macOS explicitly, then fall back to *nix `.so` as a default.

Was also wondering what the `farf` directory is? I notice that it can be over-ridden from the command line too. Is there a specific reason it needs that name? Or can we just use a temp directory?

**Comment by lijunwangs** [comment]
That names comes from vestige of the solana main code base in many places. I think it is probably just one of the  names dev made for fun and copied over repeatedly. Use a temp dir should work fine.

**Comment by levicook** [comment]
Good to know! Will try to do a bit of OS detection and remove that directory name dependency then & submit a quick PR on it today then

**Comment by levicook** [comment]
See PR #5
